### ISSUE TITLE
Question About performance

### ISSUE THREAD

**Issue by msdickinson** [mcserep/NetOctree#2]
Hi First off thanks for writting this!

I observed that when I use OctreeTree.Add over time it gets slower and slower. The checks for collsion are insanely fast.

[ OctreeTree.Add And IsColliding ]
3000 	- 0.15
30000 	- 9.05   (6X Slower on Avg)
111000 	- 238.0 (24x Slower on Avg)

[ Standard Collsion detection ]
3000     -  0.225
30000   -  11.55 (4.5X Slower)
111000   -  44.0  (5.28X Slower)

The trade off I am getting is in my test I am always adding a item after I check for collsion. and at higher numbers it seems with this test it doenst quite pay off.

On the other hand If I am often checking for collsion but not adding then the octree is much faster.

as i can do 111000  checks extreamly fast in nearly no time at all even with 111000  in the octree.

**Comment by msdickinson** [comment]
Looking closer it appears I am growing the octree to fast. every 3 items i add its create 2 more nodes in Octree.Count. This could just be user error. But I think what i want is for the tree to grow more slowly.  (instead of 1 or 2 in a in a section 10-50). I have attempted ot change  new Octree.BoundsOctree values to get it to grow less quickly. any thoughts?

**Comment by msdickinson** [comment]
After further review of the code it looks like resuing in existing bounding box and modifying its values as its pass by value made a huge differnce. I am now getting much better peformance.

[ OctreeTree.Add And IsColliding ]
3000 - 0.058
30000 - 2.9675174 (5x)
111000 - 56.9495990 (26.5x)

Note these times have addtioanal code going on this is not just a test on this libary so keep that in mind.

the perfomrance test has them all going in the same direction so its worse case.
Still intesrting to see the times get worse over time. I assume some slow down as it has to transverse though the nodes. but the Iscolliding is extreamly fast and likey has to do the same.

Anyway This is more then good enough for my purposes. Feel free to close this. Ill leave it open in case you have any thoughts on making regions larger (assuming that may help avoid making so many regions)

**Comment by mcserep** [comment]
Hello,

First, thanks for your feedback and your measurements.
You can manage how the octree grows with 2 parameters:
 - The `minNodeSize` parameter of the constructor. If the value is *too large*, you will find that the octree does not grow after a point, instead the the leaf nodes will become "overweight", containing a lot of indexed objects. This will hinder performance. *Too large* is a relative value here, it depends on how many objects would you like to index, how close they are to each other and what is the unit of measurement you are using.
- The `NumObjectsAllowed` constant member of the `BoundsOctree<T>::Node` class. (You can only modify this through altering the source code.) This configures how many objects are allowed inside a node, before it is splitted up. (Of course still not growing beyond `minNodeSize`.) Currently this is 8, you can try a higher value. There is no optimal value, you can only find a fitting balance, because by increasing `NumObjectsAllowed` you will optimize 2 factors against each other. It will:
  - decrease the performance of the operations because more objects are indexed by the nodes;
  - increase the performance of the operations, because the tree's height will be smaller.

**Comment by msdickinson** [comment]
Got it. 

I am pretty sure  I solved why it's getting worse over time. And thats due to the struct. Every time I insert and it goes down a node it has. To copy the values. I'll create a prototype pr. No need to accept it but I'll add some benchmarks with it. 

In a balanced tree it wouldn't matter as much. But for my use cases running this in blazor giving me a 50x slow down I am trying to keep this as light as possible.

**Comment by mcserep** [comment]
Well, the generic parameter `T` should be a `class` and then it will be passed by reference. The bounding box is passed by value, but ultimately it only contains 6 `float` values and even with 111000 objects inserted, the octree's height shall still be relatively small, so it is not passed around that much. Of course if your tree becomes really unbalanced, this might not be true and could be the reason for slower execution.

Anyway, if you create a PR, it is welcomed and if measurements prove significant performance boost, I will merge it of course.

**Comment by msdickinson** [comment]
Thank you. The attempt I made modifying "Point and BoundingBox" to be a class decreased the speed. My nubmers will be much smaller then what I posted in my project and they will be much more spread out. even in a worse case  it just means loading up the data from a file may take 2 seconds on blazor to build the Octree.
