### ISSUE TITLE
Add a AddAll(IEnumerable...) method if this will be faster

### ISSUE THREAD

**Issue by lschiemann** [mcserep/NetOctree#7]
We use the octree only in a "readonly mode". We add all our points to the octree directly after the ctor and then query the octree. This is very slow, when we add more than 10 mio points. Do you think that providing an Add(IEnumerable<Vector3>) method could be faster? Or can we optimize our add process somehow?

**Comment by mcserep** [comment]
Adding a new element to an octree can modify its internal structure (growing). Therefore new elements can only be added one-by-one, since in general we do not know beforehand in which directions the octree will grow.

You may try adding new elements in parallel, which can improve performance if the octree is larger. In that case a thread-safe implementation is required as mentioned in #6:
> 2. A finer grained approach is to handle the locking not on the tree, but on the nodes themselves: go down the tree, figure out where the node needs to be added, which parent nodes it will affect, wait for a lock on those, lock them, do the add operation and unlock. This will always keep the tree in a consistent state while allowing concurrent add operations in different parts of the tree. (Same for removal of nodes.) On the other hand it is much more complex to implement properly, more locks are required (1 per each node), which will effect both the memory and the computational footprint of your program.

You may also try to increase the value of `NumObjectsAllowed` in ` PointOctree<T>::Node`, so more points can be stored in a node of the octree. This will make insertion faster (but other operations, especially reading, will get slower).

**Comment by mcserep** [comment]
I will close this now, but in case you submit a PR, I would be glad to review it.
